-- AlterTable
ALTER TABLE "accessControl" ALTER COLUMN "email" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "username" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "username" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "company_name" SET DATA TYPE VARCHAR(70);
